[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x121110"
foreground = "0xdfbf8e"

[font]
size = 14

[font.bold]
family = "Source Code Pro"
style = "Semibold"

[font.bold_italic]
family = "Source Code Pro"
style = "Semibold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"},
{ key = "K", mods = "Control", action = "ScrollPageUp"  },
{ key = "J", mods = "Control", action = "ScrollPageDown"},
]

[window]
opacity = 1.0
